spring:
  profiles:
    active: dev
    include: common
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 125MB
server:
  port: 9555
upload:
  lst: E:\upload\lst
  ndvi: E:\upload\ndvi
  tvdi: E:\upload\tvdi
  uav: E:\upload\uav
py:
  jep: D:\Environment\anaconda\Lib\site-packages\jep\jep.dll

