spring:
  profiles:
    active: dev
    include: common
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 125MB
server:
  port: 9555
upload:
  photo: E:\upload\photo\
py:
  jep: D:\Environment\anaconda\Lib\site-packages\jep\jep.dll

