spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.8.193.4:3306/CAMPUS_EVENT_MANAGEMENT?serverTimezone=UTC&useSSL=false
    username: admin
    password: 9PL1rdC0U(X*__gs
  redis:
    host: localhost
    port: 6379
    database: 0